config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth' }

  resources :users, only: [:index]

  resources :articles do
  	resources :comments, only: [:create, :destroy]
  end

  resources :categories

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'users#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	validates :nume, presence: true, length: { minimum: 5, maximum: 20 }
	validates :content, presence: true
	
	has_and_belongs_to_many :categories
	belongs_to :user
	has_many :comments, dependent: :destroy
	has_one_attached :image
end

app/models/category.rb
class Category < ApplicationRecord
	validates :nume, presence: true, length: { minimum: 5 }, uniqueness: true, format: { with: /\A[a-zA-Z]+\z/,
    message: "only allows letters" }

	has_and_belongs_to_many :articles
end

app/models/comment.rb
class Comment < ApplicationRecord
	validates :content, presence: true
	
	belongs_to :state
	belongs_to :user
	belongs_to :article

    scope :published, -> { where(state_id: 1)}
	scope :archived, -> { where(state_id: 2)}
end

app/models/state.rb
class State < ApplicationRecord
	
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:facebook]
  enum user_type: [:regular_user, :admin]
  def updated_at_formatted
    updated_at.strftime("%c")
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do | user |
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
    end
  end
  has_many :articles
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  
  def index
    @articles = Article.all
  end
  
  def show

  end

  def new 
  	@article = Article.new
  end

  def create 
  	@article = Article.new article_params
  	@article.user_id = current_user.id
  	if @article.save
  	  redirect_to articles_path, notice: "Article successfully created."
    else
      render action: :new
    end
  end

  def edit

  end

  def update
  	if @article.update article_params
      redirect_to articles_path, notice: "Article successfully updated."
    else
      render action: :edit
    end
  end

  def destroy
    if @article.destroy
      redirect_to articles_path, notice: "Article successfully deleted."
    else
      redirect_to articles_path, alert: "Cannot delete article."
    end
  end

  private 
  def article_params
  	params.require(:article).permit(:nume, :content, :image, category_ids: [])
  end

  def set_article
  	@article = Article.find params[:id]
  end

  def categories
  	Category.all
  end
  helper_method :categories
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  def index
    @categories = Category.all 
  end
  def show

  end

  def new 
  	@category = Category.new
  end

  def create 
  	@category = Category.new category_params

  	if @category.save
  		redirect_to categories_path, notice: "Category successfully created."
  	else 
  		render action: :new
  	end
  end

  def edit
  
  end

  def update 
  	if @category.update category_params
  		redirect_to categories_path, notice: "Category successfully updated."
    else
      render action: :edit
    end

  end

  def destroy
    if @category.destroy
      redirect_to categories_path, notice: "Category successfully deleted."
    else
      redirect_to categories_path, alert: "Cannot delete category."
    end
  end

  private 
  def set_category
  	@category = Category.find params[:id]
  end

  def category_params
  	params.require(:category).permit(:nume)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new comment_params
    @comment.user_id = current_user.id 
    @article = Article.find(params[:article_id])
    @comment.article_id = params[:article_id]
    @comment.state_id = 1
    if @comment.save
    	
    end
    redirect_to article_path(@article)
    
  end

  def destroy
  	@article = Article.find(params[:article_id])
  	@comment = @article.comments.find(params[:id])
  	@comment.destroy
  	redirect_to article_path(@article)
  end

  private 
  def comment_params
  	params.require(:comment).permit(:content)
  end
end

app/controllers/users/omniauth_controller.rb
class Users::OmniauthController < Devise::OmniauthCallbacksController
	# facebook callback
	def facebook
  		@user = User.from_omniauth(request.env['omniauth.auth'])
  		if @user.persisted?
    		sign_in_and_redirect @user, :event => :authentication
    		set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
  		else
    		session["devise.facebook_data"] = request.env["omniauth.auth"]
    		redirect_to new_user_registration_url
  		end 
	end

	def failure
  		redirect_to root_path
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.paginate(:page => params[:page], :per_page => 2)
  	respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_error(name, msg)
    css_classes = ['alert']
    css_classes << case name
    when 'notice'
      'alert-success'
    when 'alert'
      'alert-danger'
    else
      ''
    end

    content_tag(:div, msg, class: css_classes)
  end
end

app/helpers/users/omniauth_helper.rb
module Users::OmniauthHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_article.html.erb
<div class="card" style="height: 120px">
  <div class="card-body">
    <div class="d-flex">
      <h5 class="card-title"><%= article.nume %></h5>
      <% if current_user.id == article.user.id || current_user.admin? == true %>
        <div class="dropdown ml-auto">
          <a href="#" class="text-dark" id="dropactions-group-<%= article.id %>" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          &#8801;
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropactions-group-<%= article.id %>">
            <%= link_to "Edit", edit_article_path(article), class: 'dropdown-item' %>
            <%= link_to "Delete", article_path(article), method: :delete, data: { confirm: "Are you sure?" }, class: 'dropdown-item text-danger' %>
          </div>
        </div>
      <% end -%>
    </div>
    <div><%= link_to "More details", article %></div>
  </div>
</div>

app/views/articles/_form.html.erb
<%= form_with model: article, local: true do |f| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h4><%= pluralize(article.errors.count,"error") %></h4>
      <ul>
        <% article.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :nume, value: "Nume" %>
    <%= f.text_field :nume, placeholder: "Enter a name...", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :content, value: "Content" %>
  
    <%= f.text_area :content, placeholder: "Enter content...", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.collection_check_boxes :category_ids, categories, :id, :nume, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<% if current_user.id == @article.user.id || current_user.admin? == true %>
	<h1>Edit article <%= @article.nume %></h1>

	<%= render partial: "form", locals: { article: @article } %>
<% end -%>

app/views/articles/index.html.erb
<div class="mb-3 d-flex align-items-center">
  <h2>Articles</h2>
  <%= link_to 'New', new_article_path, class: "btn btn-primary ml-auto" %>
</div>

<div class="row">
  <% @articles.each do |article| %>
    <div class="col-4">
      <%= render article %>
    </div>
  <% end %>
</div>

app/views/articles/new.html.erb
<h1>Create a new article</h1>

<%= render partial: "form", locals: { article: @article } %>

app/views/articles/show.html.erb
<div class="jumbotron">
	<h2><%= @article.nume %></h2>
	<br />
	<div style="width: 300px; height: auto">
		<%= image_tag(@article.image, style:"width: 100%") %>
	</div>
	<br />
	<p><%= @article.content %></p>
	<ul>
		<% @article.categories.each do |category| %>
  			<div class="col-4">
    			<li> <%= category.nume %></li>
  			</div>
		<% end %>
	</ul>
</div>
<h3>Comments</h3>
<% if current_user.admin? == true %>
	<%= render @article.comments %>
<% else %>
    <%= render @article.comments.published %>
<% end -%>
<br />
<h4>Add a comment:</h4>
<hr />
<%= render 'comments/form' %>

app/views/categories/_category.html.erb
<div class="card">
  <div class="card-body">
    <div class="d-flex">
      <h5 class="card-title"><%= category.nume %></h5>
      <%if current_user.admin? %>
        <div class="dropdown ml-auto">
           <a href="#" class="text-dark" id="dropactions-group-<%= category.id %>" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          &#8801;
           </a>
           <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropactions-group-<%= category.id %>">
             <%= link_to "Edit", edit_category_path(category), class: 'dropdown-item' %>
             <%= link_to "Delete", category_path(category), method: :delete, data: { confirm: "Are you sure?" }, class: 'dropdown-item text-danger' %>
           </div>
        
        </div>
      <% end -%>
    </div>

    <div><%= link_to "More details", category %></div>
  </div>
</div>

app/views/categories/_form.html.erb
<%= form_with model: category, local: true do |f| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h4><%= pluralize(category.errors.count,"error") %></h4>
      <ul>
        <% category.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :nume, value: "Nume" %>
    <%= f.text_field :nume, placeholder: "Enter a name...", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<%if current_user.admin? %>
	<h1>Edit category <%= @category.nume %></h1>
	<%= render partial: "form", locals: { category: @category } %>
<% end -%>

app/views/categories/index.html.erb
<div class="mb-3 d-flex align-items-center">
  <h2>Categories</h2>
  <%if current_user.admin? == true %>
  	<%= link_to 'New', new_category_path, class: "btn btn-primary ml-auto" %>
  <% end -%>
</div>

<div class="row">
  <% @categories.each do |category| %>
    <div class="col-4">
      <%= render category %>
    </div>
  <% end %>
</div>

app/views/categories/new.html.erb
<%if current_user.admin? %>
	<h1>Create a new category</h1>

	<%= render partial: "form", locals: { category: @category } %>
<% end -%>

app/views/categories/show.html.erb
<div class="mb-3 d-flex align-items-center">
  <h2><%= @category.nume %></h2>
  <%= link_to 'New', new_article_path, class: "btn btn-primary ml-auto" %>
</div>
<div class="row mt-3">
  <% @category.articles.each do |article| %>
    <div class="col-4">
      <%= render article %>
    </div>
  <% end %>
</div>

app/views/comments/_comment.html.erb
<hr />
<p>
  <strong>Email:</strong>
  <%= comment.user.email %>
</p>
 
<p>
  <strong>Content:</strong>
  <%= comment.content %>
</p>

<% if current_user.id == comment.user.id || current_user.admin? == true %>
	<p>
  	<%= link_to 'Delete comment', [comment.article, comment],
    	           method: :delete,
        	       data: { confirm: 'Are you sure?' } %>	
	</p>

<% end -%>

app/views/comments/_form.html.erb
<%= form_with(model: [ @article, @article.comments.build ], local: true) do |form| %>
  <div class="form-group">
    <%= form.label :content, 'Content' %>
    <%= form.text_area :content, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<header class="app-header">
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <%= link_to 'Blog', root_path, class: 'navbar-brand' %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#main-navbar">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="main-navbar">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to 'Users', users_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Categories', categories_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Articles', articles_path, class: 'nav-link' %>
        </li>
      </ul>

      <div class="navbar-text text-light ml-auto mr-1">
        <em><%= current_user.email %></em>
      </div>

      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to 'Sign out', destroy_user_session_path, method: :delete,  class: 'nav-link' %>
        </li>
      </ul>
    </div>
  </nav>
</header>

<nav class="app-nav">
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <%= render 'layouts/header' if user_signed_in? %>

    <% flash.each do |name, msg| -%>
      <%= flash_error(name, msg) %>
    <% end -%>

    <div class="container mt-3">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_form_card_row.erb
<div class="row">
  <div class="col-<%= local_assigns[:size] || 4 %> mx-auto mt-4">
    <div class="card">
      <% if local_assigns[:title].present? %>
        <div class="card-header">
          <%= title %>
        </div>
      <% end %>

      <div class="card-body">
        <%= yield %>
      </div>
    </div>
  </div>
</div>

app/views/users/_user.html.erb
<div class="card">
  <div class="card-body">
    <h5 class="card-title"><%= user.email %></h5>
    <small>Updated on <%= user.updated_at_formatted %></small>
  </div>
</div>

app/views/users/index.html.erb
<h2 class="mb-3">Users</h2>

<div class="row">
  <% @users.each do |user| %>
    <div class="col-4">
      <%= render user %>
    </div>
  <% end %>
</div>
<%= will_paginate @users %>